# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-10-02 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_user_field_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='got_inactivity_warning',
            field=models.BooleanField(default=False, verbose_name='Получил предупреждение о неактивности'),
        ),
    ]
